version: "3.8"

networks:
  safekey:
    ipam:
      driver: default
      config:
        - subnet: '192.168.3.0/24'

services:
  api:
    image: "victobonetti/ancora-connect.api:latest"
    container_name: "core-api"
    restart: always
    networks:
      safekey:
        ipv4_address: '192.168.3.1'
    depends_on:
      db:
        condition: "service_healthy"

  meet:
    image: "victobonetti/ancora-connect.meet-api:latest"
    container_name: "meet-api"
    restart: always
    networks:
      safekey:
        ipv4_address: '192.168.3.2'
    depends_on:
        api:
          condition: "service_started"

  db:
    image: "postgres:latest"
    user: postgres
    container_name: "postgres-db"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      safekey:
        ipv4_address: '192.168.3.3'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "safekey"]
      interval: 30s
      timeout: 60s
      retries: 5
